// Copyright (c) 2023-2026 Yuchi Miao <miaoyuchi@ict.ac.cn>
// SPDX-License-Identifier: MulanPSL-2.0

`ifndef ARCHINFO_DEFINE_SVH
`define ARCHINFO_DEFINE_SVH

// verilog_format: off
`define ARCHINFO_COMPONENT_ID_OFFSET      12'h000
`define ARCHINFO_VENDOR_ID_OFFSET         12'h004
`define ARCHINFO_SOC_ID_OFFSET            12'h008
`define ARCHINFO_SOC_REVISION_OFFSET      12'h00C
`define ARCHINFO_BUILD_ID_LO_OFFSET       12'h010
`define ARCHINFO_BUILD_ID_HI_OFFSET       12'h014
`define ARCHINFO_CONFIG_ID_OFFSET         12'h018
`define ARCHINFO_BUILD_STATUS_OFFSET      12'h01C
`define ARCHINFO_REFERENCE_CLOCK_OFFSET   12'h020
`define ARCHINFO_SRAM_BYTES_OFFSET        12'h024
`define ARCHINFO_TOPOLOGY_OFFSET          12'h028
`define ARCHINFO_FEATURES0_OFFSET         12'h02C
`define ARCHINFO_TECHNOLOGY_OFFSET        12'h030
`define ARCHINFO_DEVICE_ID_STATUS_OFFSET  12'h034
`define ARCHINFO_DEVICE_ID0_OFFSET        12'h038
`define ARCHINFO_DEVICE_ID1_OFFSET        12'h03C
`define ARCHINFO_DEVICE_ID2_OFFSET        12'h040
`define ARCHINFO_DEVICE_ID3_OFFSET        12'h044
`define ARCHINFO_IP_VERSION_OFFSET        12'h0F8
`define ARCHINFO_CAPABILITY_OFFSET        12'h0FC

`define ARCHINFO_COMPONENT_ID_VALUE       32'h4152_4348
`define ARCHINFO_SOC_ID_VALUE             32'h4D49_4E49
`define ARCHINFO_IP_VERSION_VALUE         32'h0002_0000
`define ARCHINFO_CAPABILITY_VALUE         32'h023F_1014

`define ARCHINFO_BUILD_DIRTY_BIT          0
`define ARCHINFO_BUILD_LOCK_VALID_BIT     1
`define ARCHINFO_BUILD_RELEASE_BIT        2
`define ARCHINFO_BUILD_SOURCE_KNOWN_BIT   3

`define ARCHINFO_DEVICE_ID_VALID_BIT      0
`define ARCHINFO_DEVICE_ID_READ_ENABLE_BIT 1
`define ARCHINFO_DEVICE_ID_READABLE_BIT   2
// verilog_format: on

`endif
