#!/usr/bin/env python3
# Copyright (c) 2023-2026 Yuchi Miao <miaoyuchi@ict.ac.cn>
# SPDX-License-Identifier: MulanPSL-2.0

from __future__ import annotations

import argparse
import json
import re
import subprocess
from pathlib import Path


def git_output(root: Path, *arguments: str) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(root), *arguments],
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return None
    return result.stdout.strip()


def source_metadata(root: Path) -> tuple[int, bool, bool]:
    revision = git_output(root, "rev-parse", "HEAD")
    known = revision is not None and re.fullmatch(r"[0-9a-fA-F]{40}", revision) is not None
    build_id = int(revision[:16], 16) if known and revision is not None else 0
    status = git_output(root, "status", "--porcelain", "--untracked-files=no")
    dirty = status is not None and status != ""
    return build_id, dirty, known


def lock_is_valid(path: Path) -> bool:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return False
    sources = data.get("sources")
    return data.get("schema_version") == 1 and isinstance(sources, dict) and bool(sources)


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(content, encoding="utf-8")
    temporary.replace(path)


def sv_header(build_id: int, config_id: int, build_status: int) -> str:
    return f"""// Generated by archinfo/scripts/generate_metadata.py. Do not edit.
`ifndef ARCHINFO_INTEGRATION_METADATA_SVH
`define ARCHINFO_INTEGRATION_METADATA_SVH

`define ARCHINFO_INTEGRATION_BUILD_ID     64'h{build_id:016X}
`define ARCHINFO_INTEGRATION_CONFIG_ID    32'h{config_id:08X}
`define ARCHINFO_INTEGRATION_BUILD_STATUS 32'h{build_status:08X}

`endif
"""


def c_header(build_id: int, config_id: int, build_status: int) -> str:
    return f"""/* Generated by archinfo/scripts/generate_metadata.py. Do not edit. */
#ifndef ARCHINFO_INTEGRATION_METADATA_H
#define ARCHINFO_INTEGRATION_METADATA_H

#include <stdint.h>

#define ARCHINFO_INTEGRATION_BUILD_ID     UINT64_C(0x{build_id:016X})
#define ARCHINFO_INTEGRATION_CONFIG_ID    UINT32_C(0x{config_id:08X})
#define ARCHINFO_INTEGRATION_BUILD_STATUS UINT32_C(0x{build_status:08X})

#endif
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate archinfo build metadata")
    parser.add_argument("--repo-root", required=True, type=Path)
    parser.add_argument("--lock", required=True, type=Path)
    parser.add_argument("--config-digest", required=True)
    parser.add_argument("--release", action="store_true")
    parser.add_argument("--output-sv", required=True, type=Path)
    parser.add_argument("--output-c", required=True, type=Path)
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if re.fullmatch(r"[0-9a-fA-F]{8,64}", args.config_digest) is None:
        raise SystemExit("--config-digest must contain 8 to 64 hexadecimal digits")

    build_id, dirty, source_known = source_metadata(args.repo_root.resolve())
    config_id = int(args.config_digest[:8], 16)
    build_status = 0
    build_status |= int(dirty) << 0
    build_status |= int(lock_is_valid(args.lock.resolve())) << 1
    build_status |= int(args.release) << 2
    build_status |= int(source_known) << 3

    atomic_write(args.output_sv, sv_header(build_id, config_id, build_status))
    atomic_write(args.output_c, c_header(build_id, config_id, build_status))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
