// Copyright (c) 2023-2026 Yuchi Miao <miaoyuchi@ict.ac.cn>
// SPDX-License-Identifier: MulanPSL-2.0

#ifndef ARCHINFO_REGS_H
#define ARCHINFO_REGS_H

#include <stdint.h>

/* Keep these hand-written definitions aligned with rtl/archinfo_define.svh. */
#define ARCHINFO_COMPONENT_ID_OFFSET        UINT32_C(0x000)
#define ARCHINFO_VENDOR_ID_OFFSET           UINT32_C(0x004)
#define ARCHINFO_SOC_ID_OFFSET              UINT32_C(0x008)
#define ARCHINFO_SOC_REVISION_OFFSET        UINT32_C(0x00C)
#define ARCHINFO_BUILD_ID_LO_OFFSET         UINT32_C(0x010)
#define ARCHINFO_BUILD_ID_HI_OFFSET         UINT32_C(0x014)
#define ARCHINFO_CONFIG_ID_OFFSET           UINT32_C(0x018)
#define ARCHINFO_BUILD_STATUS_OFFSET        UINT32_C(0x01C)
#define ARCHINFO_REFERENCE_CLOCK_OFFSET     UINT32_C(0x020)
#define ARCHINFO_SRAM_BYTES_OFFSET          UINT32_C(0x024)
#define ARCHINFO_TOPOLOGY_OFFSET            UINT32_C(0x028)
#define ARCHINFO_FEATURES0_OFFSET           UINT32_C(0x02C)
#define ARCHINFO_TECHNOLOGY_OFFSET          UINT32_C(0x030)
#define ARCHINFO_DEVICE_ID_STATUS_OFFSET    UINT32_C(0x034)
#define ARCHINFO_DEVICE_ID0_OFFSET          UINT32_C(0x038)
#define ARCHINFO_DEVICE_ID1_OFFSET          UINT32_C(0x03C)
#define ARCHINFO_DEVICE_ID2_OFFSET          UINT32_C(0x040)
#define ARCHINFO_DEVICE_ID3_OFFSET          UINT32_C(0x044)
#define ARCHINFO_IP_VERSION_OFFSET          UINT32_C(0x0F8)
#define ARCHINFO_CAPABILITY_OFFSET          UINT32_C(0x0FC)

#define ARCHINFO_COMPONENT_ID_VALUE         UINT32_C(0x41524348)
#define ARCHINFO_SOC_ID_VALUE               UINT32_C(0x4D494E49)
#define ARCHINFO_IP_VERSION_VALUE           UINT32_C(0x00020000)
#define ARCHINFO_CAPABILITY_VALUE           UINT32_C(0x023F1014)

#define ARCHINFO_BUILD_DIRTY_MASK           (UINT32_C(1) << 0U)
#define ARCHINFO_BUILD_LOCK_VALID_MASK      (UINT32_C(1) << 1U)
#define ARCHINFO_BUILD_RELEASE_MASK         (UINT32_C(1) << 2U)
#define ARCHINFO_BUILD_SOURCE_KNOWN_MASK    (UINT32_C(1) << 3U)

#define ARCHINFO_DEVICE_ID_VALID_MASK       (UINT32_C(1) << 0U)
#define ARCHINFO_DEVICE_ID_READ_ENABLE_MASK (UINT32_C(1) << 1U)
#define ARCHINFO_DEVICE_ID_READABLE_MASK    (UINT32_C(1) << 2U)
#define ARCHINFO_DEVICE_ID_WIDTH_SHIFT      8U
#define ARCHINFO_DEVICE_ID_WIDTH_MASK       (UINT32_C(0xFF) << ARCHINFO_DEVICE_ID_WIDTH_SHIFT)

#define ARCHINFO_CAPABILITY_ABI_SHIFT       24U
#define ARCHINFO_CAPABILITY_ABI_MASK        (UINT32_C(0xFF) << ARCHINFO_CAPABILITY_ABI_SHIFT)
#define ARCHINFO_ABI_VERSION                UINT32_C(2)

#endif
